default_language_version:
  python: python3.7
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/kynan/nbstripout
    rev: 0.3.7
    hooks:
    -   id: nbstripout
        files: ".ipynb"
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        additional_dependencies: ['toml']
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -    id: flake8
         additional_dependencies: ['flake8-docstrings==1.5.0', 'darglint==1.2.1']
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ['-p=pyrh']
        pass_filenames: false
